
##        ░█████╗░███╗░░██╗████████╗██╗███████╗░█████╗░░██████╗████████╗██████╗░██████╗░███████╗░█████╗░██╗░░██╗
##        ██╔══██╗████╗░██║╚══██╔══╝██║██╔════╝██╔══██╗██╔════╝╚══██╔══╝██╔══██╗██╔══██╗██╔════╝██╔══██╗██║░██╔╝
##        ███████║██╔██╗██║░░░██║░░░██║█████╗░░███████║╚█████╗░░░░██║░░░██████╦╝██████╔╝█████╗░░███████║█████═╝░
##        ██╔══██║██║╚████║░░░██║░░░██║██╔══╝░░██╔══██║░╚═══██╗░░░██║░░░██╔══██╗██╔══██╗██╔══╝░░██╔══██║██╔═██╗░
##        ██║░░██║██║░╚███║░░░██║░░░██║██║░░░░░██║░░██║██████╔╝░░░██║░░░██████╦╝██║░░██║███████╗██║░░██║██║░╚██╗
##        ╚═╝░░╚═╝╚═╝░░╚══╝░░░╚═╝░░░╚═╝╚═╝░░░░░╚═╝░░╚═╝╚═════╝░░░░╚═╝░░░╚═════╝░╚═╝░░╚═╝╚══════╝╚═╝░░╚═╝╚═╝░░╚═╝

#Notify settings
# {PLAYER} - Player nickname
# {WHAT} - cheat level or type
notify:
  permission: "ac.notify"
  alert: "&bAntyCheat: &3{PLAYER} &fis suspected of: &3{WHAT}!"

#Automatic bans settings

#Bans are only given for one type of notification, because  --->
#the other one is just a warning that the player may be in possession of something

# {PLAYER} - Player nickname
# {WHAT} - cheat level or type
bans:
  status: false
  ban-command: "ban {PLAYER} Cheat-{WHAT}"